### ISSUE TITLE
Starting web service when sending

### ISSUE THREAD

**Issue by ilius** [meowrain/localsend-go#3]
Hello
I have a question.

[This web service and handlers that we register](https://github.com/meowrain/localsend-go/blob/main/cmd/main.go#L29):

```go
	if config.ConfigData.Functions.HttpFileServer {

		//如果启用http文件服务器，启用下面的路由
		httpServer.HandleFunc("/", handlers.IndexFileHandler)
		httpServer.HandleFunc("/uploads/", handlers.FileServerHandler)
		httpServer.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.FS(static.EmbeddedStaticFiles))))
	}
	/*发送接收部分*/
	if config.ConfigData.Functions.LocalSendServer {

		httpServer.HandleFunc("/api/localsend/v2/prepare-upload", handlers.PrepareReceive)
		httpServer.HandleFunc("/api/localsend/v2/upload", handlers.ReceiveHandler)
		httpServer.HandleFunc("/api/localsend/v2/info", handlers.GetInfoHandler)
		httpServer.HandleFunc("/send", handlers.NormalSendHandler)       // 上传处理程序
		httpServer.HandleFunc("/receive", handlers.NormalReceiveHandler) // 下载处理程序

	}
```

Do they serve any purpose **when you are sending a file** to another machine? (with `-mode send` flag)
Because I disabled the `httpServer` entirely, and it sends the file successfully.

The program exits when it's done sending the file, do it doesn't make sense to receive files from a third machine at the same time.

**Comment by meowrain** [comment]
> Hello I have a question.
> 
> [This web service and handlers that we register](https://github.com/meowrain/localsend-go/blob/main/cmd/main.go#L29):
> 
> ```go
> 	if config.ConfigData.Functions.HttpFileServer {
> 
> 		//如果启用http文件服务器，启用下面的路由
> 		httpServer.HandleFunc("/", handlers.IndexFileHandler)
> 		httpServer.HandleFunc("/uploads/", handlers.FileServerHandler)
> 		httpServer.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.FS(static.EmbeddedStaticFiles))))
> 	}
> 	/*发送接收部分*/
> 	if config.ConfigData.Functions.LocalSendServer {
> 
> 		httpServer.HandleFunc("/api/localsend/v2/prepare-upload", handlers.PrepareReceive)
> 		httpServer.HandleFunc("/api/localsend/v2/upload", handlers.ReceiveHandler)
> 		httpServer.HandleFunc("/api/localsend/v2/info", handlers.GetInfoHandler)
> 		httpServer.HandleFunc("/send", handlers.NormalSendHandler)       // 上传处理程序
> 		httpServer.HandleFunc("/receive", handlers.NormalReceiveHandler) // 下载处理程序
> 
> 	}
> ```
> 
> Do they serve any purpose **when you are sending a file** to another machine? (with `-mode send` flag) Because I disabled the `httpServer` entirely, and it sends the file successfully.
> 
> The program exits when it's done sending the file, do it doesn't make sense to receive files from a third machine at the same time.

I initially planned to develop a command-line program that could be used both as a local cloud drive and for temporary file transfer. So I wrote the web part, implementing functionalities similar to a NAS. At the time, I was also considering adding file management and image management features to the web interface, but I didn't continue the development due not having enough time.

**Comment by ilius** [comment]
No worries.

I just wanted to make sure they are not needed so I can disable them for sending.
Thanks.

I was thinking about a TUI or Test-based user interface like lazydocker and lazygit, so I can run it on any Unix machine, even *BSD, even with no GUI.
But it serves the purpose right now.
